const express = require("express")
const connectDB = require("./config/db")
const dotenv = require("dotenv")
const app = express()
const dns=require("dns")
const authRoute = require("./routes/authRoutes")
const courseRoute = require("./routes/courseRoutes")
const cors = require("cors")

app.use(express.json())
app.use(cors())
app.use("/api/auth", authRoute)
dns.setServers(["1.1.1.1","8.8.8.8"])
dotenv.config()
app.use("/api/course",  courseRoute)
connectDB()

app.listen(3000, ()=>{
    console.log("listening to the port")
})